services:
  - type: web
    name: franchise-api
    runtime: java
    plan: free
    branch: master
    autoDeploy: true
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Xms128m -Xmx384m -jar target/franchise-api-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
