spring:
  application:
    name: franchise-api
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://db.vehadvbrxuiysspufvju.supabase.co:5432/postgres?sslMode=require}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}

server:
  port: ${PORT:8080}
  error:
    include-message: never
